# Generated by Django 5.0.6 on 2024-08-05 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Pantry', 'Pantry'), ('Chilled', 'Chilled'), ('Frozen', 'Frozen'), ('Supliment', 'Supliment'), ('Prescription', 'Prescription')], max_length=20, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('units', models.CharField(choices=[('grams', 'grams'), ('ml', 'ml'), ('bags', 'bags'), ('cans', 'cans'), ('packs', 'packs'), ('kg', 'kg'), ('doses', 'doses')], null=True)),
                ('added', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Inventory Items',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.goods')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
