# Generated by Django 5.0.6 on 2024-08-02 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_food_medicine_neededitem_delete_kitchen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name_plural': 'Food'},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name_plural': 'Med Cabinet'},
        ),
        migrations.AlterModelOptions(
            name='neededitem',
            options={'verbose_name_plural': 'Shopping List'},
        ),
        migrations.AddField(
            model_name='medicine',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='neededitem',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
