# Generated by Django 5.0.6 on 2024-08-02 23:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_food_options_alter_medicine_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeededItem',
            new_name='Grocery',
        ),
    ]
