# Generated by Django 5.0.6 on 2024-08-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_neededitem_grocery'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='units',
            field=models.CharField(choices=[('grams', 'grams'), ('ml', 'ml'), ('bags', 'bags'), ('cans', 'cans'), ('packs', 'packs'), ('kg', 'kg'), ('doses', 'doses')], null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='units',
            field=models.CharField(choices=[('grams', 'grams'), ('ml', 'ml'), ('bags', 'bags'), ('cans', 'cans'), ('packs', 'packs'), ('kg', 'kg'), ('doses', 'doses')], null=True),
        ),
    ]
