# Generated by Django 5.0.6 on 2024-08-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_medicine_units_alter_food_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='quantity',
            new_name='doses',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='units',
        ),
        migrations.AlterField(
            model_name='food',
            name='units',
            field=models.CharField(choices=[('grams', 'grams'), ('ml', 'ml'), ('bags', 'bags'), ('cans', 'cans'), ('packs', 'packs'), ('kg', 'kg')], null=True),
        ),
    ]
